BankSystem(MVC)/Controllers/AccoutController.cs
using BankSystem_MVC_.Data;
using BankSystem_MVC_.Models;
using Microsoft.AspNetCore.Mvc;

namespace BankSystem_MVC_.Controllers
{
    public class AccoutController : Controller
    {
        private readonly BankDbContext _bankDbContext;

        public AccoutController(BankDbContext bankDbContext)
        {
            _bankDbContext = bankDbContext;
        }
        public IActionResult Add()
        {
            try
            {
                var accountlist = _bankDbContext.Account.ToList();
                return View(accountlist);

            }
            catch (Exception ex)
            {
                return View();
            }
        }
        public IActionResult AddAccount()
        {
            return View();
        } // Handle the account creation form submission

        [HttpPost]
        public ActionResult Create(Account account)
        {
            _bankDbContext.Account.Add(account);
            _bankDbContext.SaveChanges();
            return RedirectToAction("Add");
        }
    }
}

BankSystem(MVC)/Controllers/DepositeController.cs
using AutoMapper;
using BankSystem_MVC_.Data;
using BankSystem_MVC_.Dto;
using BankSystem_MVC_.Models;
using BankSystem_MVC_.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BankSystem_MVC_.Controllers
{
    public class DepositeController : Controller
    {
        private readonly BankDbContext _bankDbContext;
        private readonly IMapper _mapper;
        private readonly IEmailRepository _emailRepository;

        public DepositeController(BankDbContext bankDbContext, IMapper mapper,IEmailRepository emailRepository)
        {
            _bankDbContext = bankDbContext;
            _mapper = mapper;
            _emailRepository = emailRepository;
        }
        public IActionResult DepositeAccount()
        {
            try
            {
                var accountlist = _bankDbContext.Deposite.ToList();
                return View(accountlist);

            }
            catch (Exception ex)
            {
                return View();
            }

        }
        public IActionResult AddDeposit()
        {
            return View();
        }
       

        [HttpPost]
        public  IActionResult CreateDeposite(DepositeDto depositeDto)
        {
            if (depositeDto.DepositeAmount <= 0)
            {
                throw new ArgumentException("Deposite amount must be greater then Zero");
            }
            using (var transcation = _bankDbContext.Database.BeginTransaction())
            {
                {
                    try
                    {
                        ViewBag.Message = "Hi, Dot Net Tricks";
                        var account = _bankDbContext.Account.FirstOrDefault(e => e.Id == depositeDto.AccountId);
                        if (account == null)
                        {
                            throw new ArgumentException("Account Not Found");
                        }
                        var deposite = _mapper.Map<Deposite>(depositeDto);
                        _bankDbContext.Deposite.Add(deposite);
                        _bankDbContext.SaveChanges();

                        var users = _mapper.Map<DepositeDto>(deposite);
                        account.CurrentBalance = account.CurrentBalance + depositeDto.DepositeAmount;
                        _bankDbContext.Account.Update(account);
                        _bankDbContext.SaveChanges();
                        transcation.Commit();
                        var mailRequest = new MailRequest()
                        {
                            ToEmail = account.Email,
                            Subject = "Deposite Confirmation",
                            Body = $"{account.FirstName},your deposite of {depositeDto.DepositeAmount} has succesfully processed."

                        };
                         _emailRepository.SendEmailAsync(mailRequest);
                        ViewBag.Msg = ViewBag.Message;
                        return RedirectToAction("DepositeAccount");


                    }
                    catch (Exception ex)
                    {
                        transcation.RollbackAsync();

                        return RedirectToAction("DepositeAccount");
                    }
                }


            }
        }
    }
}

BankSystem(MVC)/Controllers/OtpController.cs
using BankSystem_MVC_.Data;
using BankSystem_MVC_.Dto;
using BankSystem_MVC_.Models;
using BankSystem_MVC_.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BankSystem_MVC_.Controllers
{
    public class OtpController : Controller
    {
        private readonly BankDbContext _bankDbContext;
        private readonly IEmailRepository _emailRepository;

        public OtpController(BankDbContext bankDbContext, IEmailRepository emailRepository)
        {
            _bankDbContext = bankDbContext;
            _emailRepository = emailRepository;
        }

        public IActionResult Add()
        {
            try
            {
                var accountList = _bankDbContext.Otp.ToList();
                return View(accountList);
            }
            catch (Exception ex)
            {
                // Log the exception here
                return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }

        public IActionResult AddOtp()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateOtp(int accountId)
        {
            try
            {
                
                var account = await _bankDbContext.Account.FirstOrDefaultAsync(e => e.Id == accountId);

                if (account == null)
                {
                    return BadRequest($"Account with ID {accountId} does not exist.");
                }

                var existingOtp = await _bankDbContext.Otp
                    .Where(e => e.AccountId == accountId && e.ExpiryDate > DateTime.Now)
                    .FirstOrDefaultAsync();

                if (existingOtp != null)
                {
                    return Ok(existingOtp.Code);
                }

                var otpCode = GenerateRandomOtp();
                var otp = new Otp
                {
                    AccountId = account.Id,
                    Code = otpCode,
                    ExpiryDate = DateTime.Now.AddMinutes(2),
                    IsUsed = false
                };

                _bankDbContext.Otp.Add(otp);
                await _bankDbContext.SaveChangesAsync();

                var mailRequest = new MailRequest
                {
                    ToEmail = account.Email,
                    Subject = "OTP for Transfer Confirmation",
                    Body = $"Your OTP for transfer is: {otpCode}"
                };

                await _emailRepository.SendEmailAsync(mailRequest);
                // return Ok(otpCode);
                return Ok("Generating the Otp succesfully");
            }
            catch (Exception ex)
            {
                // Log the exception here
                return StatusCode(500, "Internal server error.");
            }
        }

        private string GenerateRandomOtp()
        {
            Random random = new Random();
            return random.Next(100000, 999999).ToString();
        }

        public IActionResult VerifyOtp()
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> Verify(int accountId,string Code)
       // public async Task<IActionResult> Verify(int accountId, string otpCode)
        {
            try
            {
                var account = await _bankDbContext.Account.Where(e => e.Id == accountId).FirstOrDefaultAsync();


                // var account = await _bankDbContext.Account.FirstOrDefaultAsync(e => e.Id == accountId);

                if (account == null)
                {
                   // ViewData["Message"] = "AccountId Does Not Exist.";
                    throw new ArgumentException($"Account with ID {accountId} does not exist.");
                }
                var otp = await _bankDbContext.Otp
                    .Where(e => e.AccountId == accountId && e.Code == Code && e.ExpiryDate > DateTime.Now)
                    .FirstOrDefaultAsync();

                if (otp != null)
                {
                    otp.IsUsed = true;
                    _bankDbContext.Otp.Update(otp);
                    await _bankDbContext.SaveChangesAsync();
                    return true;
                }
                return false;
            }
            catch (Exception ex)
            {
                throw new Exception("Error verifying OTP", ex);
            }

        }
    }
}

BankSystem(MVC)/Controllers/TransferController.cs
using AutoMapper;
using BankSystem_MVC_.Data;
using BankSystem_MVC_.Dto;
using BankSystem_MVC_.Models;
using BankSystem_MVC_.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace BankSystem_MVC_.Controllers
{
    public class TransferController : Controller
    {
        private readonly BankDbContext _bankDbContext;
        private readonly IEmailRepository _emailRepository;
        private readonly IMapper _mapper;

        public TransferController(BankDbContext bankDbContext, IMapper mapper,IEmailRepository emailRepository)
        {
            _bankDbContext = bankDbContext;
            _emailRepository = emailRepository;
            _mapper = mapper;
        }

        public IActionResult TransferAccount()
        {
            try
            {
                var accountList = _bankDbContext.Transfer.ToList();
                return View(accountList);
            }
            catch (Exception ex)
            {
                // Log exception here
                return View(); // Optionally pass an error message to the view
            }
        }

        public IActionResult AddTransfer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateTransfer(TransferDto transferDto)
        {
            try
            {
                var otp =  _bankDbContext.Otp
                    .FirstOrDefault(e => e.AccountId == transferDto.AccountId && e.IsUsed == true);

                if (otp == null)
                {
                    throw new Exception("OTP invalid");
                }
                var dateTime = DateTime.Now;
                if (dateTime > otp.ExpiryDate)
                {
                    _bankDbContext.Remove(otp);
                    _bankDbContext.SaveChanges();
                    throw new Exception("OTP will be expire");
                }

                if (transferDto.TransferAmount <= 0)
                {
                    return BadRequest("Transfer amount must be greater than zero.");
                }

                using (var transaction = _bankDbContext.Database.BeginTransaction())
                {
                    try
                    {
                        var senderAccount = _bankDbContext.Account.FirstOrDefault(e => e.Id == transferDto.SenderId);
                        if (senderAccount == null)
                        {
                            return NotFound("Sender account not found.");
                        }

                        var receiverAccount = _bankDbContext.Account.FirstOrDefault(e => e.Id == transferDto.ReceiverId);
                        if (receiverAccount == null)
                        {
                            return NotFound("Receiver account not found.");
                        }

                        if (senderAccount.CurrentBalance < transferDto.TransferAmount)
                        {
                            return BadRequest("Insufficient balance.");
                        }

                        senderAccount.CurrentBalance -= transferDto.TransferAmount;
                        receiverAccount.CurrentBalance += transferDto.TransferAmount;

                        _bankDbContext.Account.Update(senderAccount);
                        _bankDbContext.Account.Update(receiverAccount);

                        var transfer = _mapper.Map<Transfer>(transferDto);
                        _bankDbContext.Transfer.Add(transfer);
                       _bankDbContext.Otp.Remove(otp);

                        _bankDbContext.SaveChanges();
                        transaction.Commit();
                        var senderEmailRequest = new MailRequest
                        {
                            ToEmail = senderAccount.Email,
                            Subject = "Transfer Confirmation",
                            Body = $"{senderAccount.FirstName}, you have successfully transferred {transferDto.TransferAmount} to {receiverAccount.FirstName}. Your new balance is {senderAccount.CurrentBalance}."
                        };
                        _emailRepository.SendEmailAsync(senderEmailRequest);

                        var receiverEmailRequest = new MailRequest
                        {
                            ToEmail = receiverAccount.Email,

                            Subject = "Transfer Confirmation",
                            Body = $"{receiverAccount.FirstName}, you have received {transferDto.TransferAmount} from {senderAccount.FirstName}. Your new balance is {receiverAccount.CurrentBalance}."
                        };
                         _emailRepository.SendEmailAsync(receiverEmailRequest);
                       

                       return Ok(_mapper.Map<TransferDto>(transfer));
                        //RedirectToAction("TransferAccount");
                    }
                    catch (Exception ex)
                    {
                         transaction.Rollback();
                        return StatusCode(500, "Internal server error.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Log exception here
                return StatusCode(500, "Internal server error.");
            }
        }
    }
}

BankSystem(MVC)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankSystem_MVC_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BankSystem_MVC_.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BankSystem_MVC_</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accout" asp-action="AddAccount">AddAccount</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deposite" asp-action="AddDeposit">AddDeposit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Withdraw" asp-action="AddWithdraw">AddWithdraw</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="AddTransfer">AddTransfer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Otp" asp-action="AddOtp">AddOtp</a>
                        </li>

                      @*   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="AddEmail">AddEmail</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BankSystem_MVC_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>